### ISSUE TITLE
logging in problems

### ISSUE THREAD

**Issue by Coderrrrrrrrrrr** [wechaty/puppet-xp#115]
When I try to start the example in the [(https://github.com/wechaty/puppet-xp)]
it comes up with an error

C:\Users\chensn\Documents\puppet-xp-main>npm start

> wechaty-puppet-xp@1.11.12 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

'cross-env' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by atorber** [comment]
Are you sure you have installed the NPM dependency package? 
Try to run `npm install`, then run `npm start`, follow this step, and then let me know the result.

**Comment by Coderrrrrrrrrrr** [comment]
> Are you sure you have installed the NPM dependency package? Try to run `npm install`, then run `npm start`, follow this step, and then let me know the result.

Thank you for replying. I solved the 'cross-env' problem by running this command line:
cnpm i cross-env --save-dev

And there comes up with another error:
SyntaxError: Cannot use import statement outside a module

Then I'm totally stuck now. By the way, 'npm install' already executed.
