### ISSUE TITLE
 no such file or directory, stat 'E:\docs\images\wechaty-icon.png'

### ISSUE THREAD

**Issue by leochen-g** [wechaty/puppet-xp#129]
![image](https://user-images.githubusercontent.com/20028566/178424084-fd9ccc43-4e84-48d6-bea5-86318c0eaac5.png)

会遇到默认头像找不到的情况，看到代码里对头像是取得相对位置，但是打包的时候并不会把头像打包进去，而且这个位置是相对于命令执行的目录来算相对路径的，建议可以更换为默认的base64 图片或者一个在线图片
![image](https://user-images.githubusercontent.com/20028566/178424262-0cc7652f-76b4-4c9a-b631-371839401848.png)

**Comment by atorber** [comment]
I guess this problem occurs when you call `Contact.avatar() ⇒ Promise <FileBox>` method.

In fact, XP does not support this method yet, so a fixed value is written at present, and I will optimize this problem in the next version.

Thanks for your attention.
