### ISSUE TITLE
It seems that it can only download thumbnails

### ISSUE THREAD

**Issue by jackatls** [wechaty/puppet-xp#132]
I failed to download the original image in the examples and only can get the thumbnail when an Image is received.It seems that the original image can be downloaded only by clicking the thumbnail on the wechat-PC.Is there a way to solve this?

**Comment by choogoo** [comment]
HD is supported since version 1.12.3.update run `npm install wechaty-puppet-xp@1.12.3` and update your wechat to 3.6.0.18 on pc.

**Comment by jackatls** [comment]
> 

thanks!
