### ISSUE TITLE
群列表 and 好友列表，无法获取，返回的是空

### ISSUE THREAD

**Issue by kingkasuo** [wechaty/puppet-xp#133]
const roomList = bot.Room.findAll()
log.info('TestBot room count:', roomList.length)

const contactList = bot.Contact.findAll()
log.info('TestBot contact count:', contactList.length)
![Screenshot_1](https://user-images.githubusercontent.com/792288/188354981-d31a4b42-7d40-4f68-a534-4bea790b4f2a.png)

**Comment by atorber** [comment]
This seems to be a usage problem, upgrade to the latest version, then run `npm run start:ripe` to see if the same problem still exists
