### ISSUE TITLE
npm i wechaty-puppet-xp失败，windows跟mac都尝试了

### ISSUE THREAD

**Issue by liziwork** [wechaty/puppet-xp#168]
是不是对系统环境有什么要求，需要提前安装一些依赖。

npm i wechaty-puppet-xp
npm ERR! code 1
npm ERR! path /Users/lizi/Work/WechatBotTest/node_modules/frida
npm ERR! command failed
npm ERR! command sh -c prebuild-install || node-gyp rebuild
npm ERR! prebuild-install warn install Request timed out
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@16.16.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Applications/Xcode.app/Contents/Developer/usr/bin/python3"
npm ERR! gyp info spawn /Applications/Xcode.app/Contents/Developer/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/lizi/Work/WechatBotTest/node_modules/frida/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/lizi/Library/Caches/node-gyp/16.16.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/lizi/Library/Caches/node-gyp/16.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/lizi/Library/Caches/node-gyp/16.16.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/lizi/Work/WechatBotTest/node_modules/frida',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp: binding.gyp not found (cwd: /Users/lizi/Work/WechatBotTest/node_modules/frida) while trying to load binding.gyp
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /Users/lizi/Work/WechatBotTest/node_modules/frida
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lizi/.npm/_logs/2022-12-28T13_31_33_308Z-debug-0.log

**Comment by liziwork** [comment]
.../frida@15.2.2/node_modules/frida install: prebuild-install warn install read ECONNRESET
.../frida@15.2.2/node_modules/frida install: F:\WechatTest\node_modules\.pnpm\frida@15.2.2\node_modules\frida>if not defined npm_config_node_gyp (node "F:\node\node_modules\pnpm\dist\node-gyp-bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "F:\node\node_modules\pnpm\dist\node_modules\node-gyp\bin\node-gyp.js" rebuild )
.../frida@15.2.2/node_modules/frida install: gyp info it worked if it ends with ok
.../frida@15.2.2/node_modules/frida install: gyp info using node-gyp@9.1.0
.../frida@15.2.2/node_modules/frida install: gyp info using node@16.17.0 | win32 | x64
.../frida@15.2.2/node_modules/frida install: gyp info find Python using Python version 3.7.9 found at "D:\Python\python3.7.0\python.exe"
.../frida@15.2.2/node_modules/frida install: gyp info find VS using VS2022 (17.4.33205.214) found at:
.../frida@15.2.2/node_modules/frida install: gyp info find VS "F:\Microsoft"
.../frida@15.2.2/node_modules/frida install: gyp info find VS run with --verbose for detailed information
.../frida@15.2.2/node_modules/frida install: gyp info spawn D:\Python\python3.7.0\python.exe
.../frida@15.2.2/node_modules/frida install: gyp info spawn args [
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   'F:\\node\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\gyp\\gyp_main.py',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   'binding.gyp',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-f',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   'msvs',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-I',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   'F:\\WechatTest\\node_modules\\.pnpm\\frida@15.2.2\\node_modules\\frida\\build\\config.gypi',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-I',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   'F:\\node\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\addon.gypi',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-I',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   'C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\16.17.0\\include\\node\\common.gypi',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-Dlibrary=shared_library',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-Dvisibility=default',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\AppData\\Local\\node-gyp\\Cache\\16.17.0',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-Dnode_gyp_dir=F:\\node\\node_modules\\pnpm\\dist\\node_modules\\node-gyp',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.17.0\\\\<(target_arch)\\\\node.lib',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-Dmodule_root_dir=F:\\WechatTest\\node_modules\\.pnpm\\frida@15.2.2\\node_modules\\frida',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-Dnode_engine=v8',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '--depth=.',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '--no-parallel',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '--generator-output',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   'F:\\WechatTest\\node_modules\\.pnpm\\frida@15.2.2\\node_modules\\frida\\build',
.../frida@15.2.2/node_modules/frida install: gyp info spawn args   '-Goutput_dir=.'
.../frida@15.2.2/node_modules/frida install: gyp info spawn args ]
.../frida@15.2.2/node_modules/frida install: gyp: binding.gyp not found (cwd: F:\WechatTest\node_modules\.pnpm\frida@15.2.2\node_modules\frida) while trying to load binding.gyp
.../frida@15.2.2/node_modules/frida install: gyp ERR! configure error
.../frida@15.2.2/node_modules/frida install: gyp ERR! stack Error: `gyp` failed with exit code: 1
.../frida@15.2.2/node_modules/frida install: gyp ERR! stack     at ChildProcess.onCpExit (F:\node\node_modules\pnpm\dist\node_modules\node-gyp\lib\configure.js:284:16)
.../frida@15.2.2/node_modules/frida install: gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
.../frida@15.2.2/node_modules/frida install: gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
.../frida@15.2.2/node_modules/frida install: gyp ERR! System Windows_NT 10.0.19041
.../frida@15.2.2/node_modules/frida install: gyp ERR! command "F:\\node\\node.exe" "F:\\node\\node_modules\\pnpm\\dist\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
.../frida@15.2.2/node_modules/frida install: gyp ERR! cwd F:\WechatTest\node_modules\.pnpm\frida@15.2.2\node_modules\frida
.../frida@15.2.2/node_modules/frida install: gyp ERR! node -v v16.17.0
.../frida@15.2.2/node_modules/frida install: gyp ERR! node-gyp -v v9.1.0
.../frida@15.2.2/node_modules/frida install: gyp ERR! not ok
.../frida@15.2.2/node_modules/frida install: Failed
 ELIFECYCLE  Command failed with exit code 1.

**Comment by liziwork** [comment]
梯子的问题。。。已解决

**Comment by zhuhaier1992** [comment]
> 梯子的问题。。。已解决

能否请教是怎么解决的吗？我关了梯子、开着rule或global，从梯子打开cmd都不行
