### ISSUE TITLE
在login事件接收到之前,如果收到其他的消息,会崩溃.

### ISSUE THREAD

**Issue by aishiqi** [wechaty/puppet-xp#175]
如果微信已经登录,运行此程序会等待一段时间(刚好20秒)才收到login事件,如果在此之前收到别人发送的消息, 程序会崩溃.
`__currentUserId `是在login事件里面被设置的.

```
06:06:19 INFO StarterBot Starter Bot Started.
file:///C:/MyPC/puppet-xp/node_modules/wechaty-puppet/src/mixins/login-mixin.ts:25
        throw new Error('not logged in, no this.__currentUserId yet.')
              ^
Error: not logged in, no this.__currentUserId yet.
    at PuppetXp.currentUserId (file:///C:/MyPC/puppet-xp/node_modules/wechaty-puppet/src/mixins/login-mixin.ts:25:15)
    at PuppetXp.onHookRecvMsg (file:///C:/MyPC/puppet-xp/src/puppet-xp.ts:359:19)
    at WeChatSidecar.<anonymous> (file:///C:/MyPC/puppet-xp/src/puppet-xp.ts:117:16)
    at WeChatSidecar.emit (node:events:513:28)
    at WeChatSidecar.emit (node:domain:489:12)
    at WeChatSidecar.[hookEventHandler] (file:///C:/MyPC/puppet-xp/node_modules/sidecar/src/sidecar-body/sidecar-body.ts:450:10)
    at WeChatSidecar.[scriptMessageHandler] (file:///C:/MyPC/puppet-xp/node_modules/sidecar/src/sidecar-body/sidecar-body.ts:372:35)
    at C:\MyPC\puppet-xp\node_modules\frida\dist\script.js:95:21
```

**Comment by yeguobin8** [comment]
同样遇到这种情况，是啥问题？

C:\Users\xmygb\Desktop\test\wechaty-puppet-xp>npm start

> wechaty-puppet-xp@1.13.8 start
> cross-env NODE_OPTIONS="--no-warnings --loader=ts-node/esm" node examples/ding-dong-bot.ts

15:50:23 INFO options... {"wechatVersion":"3.9.2.23"}

Puppet Version: 0.0.0

Please wait... I'm trying to login in...


msgType 49
file:///C:/Users/xmygb/Desktop/test/wechaty-puppet-xp/node_modules/wechaty-puppet/src/mixins/login-mixin.ts:25
        throw new Error('not logged in, no this.__currentUserId yet.')
              ^
Error: not logged in, no this.__currentUserId yet.
    at PuppetXp.currentUserId (file:///C:/Users/xmygb/Desktop/test/wechaty-puppet-xp/node_modules/wechaty-puppet/src/mixins/login-mixin.ts:25:15)
    at PuppetXp.onHookRecvMsg (file:///C:/Users/xmygb/Desktop/test/wechaty-puppet-xp/src/puppet-xp.ts:373:19)
    at WeChatSidecar.<anonymous> (file:///C:/Users/xmygb/Desktop/test/wechaty-puppet-xp/src/puppet-xp.ts:120:16)
    at WeChatSidecar.emit (node:events:513:28)
    at WeChatSidecar.emit (node:domain:489:12)
    at WeChatSidecar.[hookEventHandler] (file:///C:/Users/xmygb/Desktop/test/wechaty-puppet-xp/node_modules/sidecar/src/sidecar-body/sidecar-body.ts:450:10)
    at WeChatSidecar.[scriptMessageHandler] (file:///C:/Users/xmygb/Desktop/test/wechaty-puppet-xp/node_modules/sidecar/src/sidecar-body/sidecar-body.ts:372:35)
    at C:\Users\xmygb\Desktop\test\wechaty-puppet-xp\node_modules\frida\dist\script.js:95:21

**Comment by huan** [comment]
I think this is a known issue:  Wechaty need to delay process any events from the puppet before the `login` event emitted, because all other event processing needs current user information, which only will be ready after processed the `login` event.

what version of Wechaty are you using? Have you tried the latest version of Wechaty, does the problem still exist?

**Comment by yeguobin8** [comment]
> I think this is a known issue: Wechaty need to delay process any events from the puppet before the `login` event emitted, because all other event processing needs current user information, which only will be ready after processed the `login` event.
> 
> what version of Wechaty are you using? Have you tried the latest version of Wechaty, does the problem still exist?

我用另外一个微信号（群和好友都比较少）登入期间信息少，这个微信就没问题。目前观察：就是在登入期间有接收大量信息就是出现这种错误。

Wechaty版本信息：
  "node_modules/wechaty": {
      "version": "1.20.2",
      "resolved": "https://registry.npmjs.org/wechaty/-/wechaty-1.20.2.tgz",
      "integrity": "sha512-bIZ8m2lOya4SKnxVunbMGemE8JyZdnXhnLnfXtBAZV997ef6uqP4pJxuwiJnV0qbXGyIE+F3B2b8yjQOZh43lQ==",
      "dev": true,
      "dependencies": {
        "clone-class": "^1.1.1",
        "cmd-ts": "^0.10.0",
        "cockatiel": "^2.0.2",
        "cross-spawn": "^7.0.3",
        "dotenv": "^16.0.0",
        "file-box": "^1.4.15",
        "fp-ts": "^2.11.9",
        "gerror": "^1.0.16",
        "get-port": "^6.1.2",
        "json-rpc-peer": "^0.17.0",
        "memory-card": "^1.1.2",
        "open-graph": "^0.2.6",
        "rx-queue": "^1.0.5",
        "state-switch": "^1.6.3",
        "uuid": "^8.3.2",
        "wechaty-puppet": "^1.20.1",
        "wechaty-puppet-service": "^1.19.8",
        "wechaty-puppet-wechat4u": "^1.11.1",
        "wechaty-token": "^1.1.1",
        "ws": "^8.5.0"
      },
      "bin": {
        "wechaty": "dist/esm/bin/cli.js",
        "wechaty-doctor": "dist/esm/bin/doctor.js",
        "wechaty-io-client": "dist/esm/bin/io-client.js",
        "wechaty-puppet-install": "dist/esm/bin/puppet-install.js",
        "wechaty-version": "dist/esm/bin/version.js"
      },
      "engines": {
        "node": ">=16",
        "npm": ">=7"
      },
      "funding": {
        "type": "opencollective",
        "url": "https://opencollective.com/wechaty"
      }
    },
    "node_modules/wechaty-grpc": {
      "version": "1.5.2",
      "resolved": "https://registry.npmjs.org/wechaty-grpc/-/wechaty-grpc-1.5.2.tgz",
      "integrity": "sha512-oOXU62oDf8/LIg8wAqSoZogZ+NFSGIAJvYuTewR6x5Ia4iWjbfrlwy7NHjWGBLkKM2EpnxgOAjyxhAb1iMxTJg==",
      "dev": true,
      "dependencies": {
        "@grpc/grpc-js": "^1.3.7",
        "google-protobuf": "^3.18.0",
        "stronger-typed-streams": "^0.2.0"
      },
      "engines": {
        "node": ">=16",
        "npm": ">=7"
      }
    },
    "node_modules/wechaty-puppet": {
      "version": "1.20.2",
      "resolved": "https://registry.npmjs.org/wechaty-puppet/-/wechaty-puppet-1.20.2.tgz",
      "integrity": "sha512-IXcnUc9A3hGIT+9CEF8KLkbdld+AQPfVlWLeUXmmSvm3I9NbSbVfU43FZvKMjvLCexvN5DZq2+JZdASESohI5Q==",
      "dependencies": {
        "@alloc/quick-lru": "^5.2.0",
        "brolog": "^1.14.2",
        "clone-class": "^1.1.1",
        "file-box": "^1.4.13",
        "fp-ts": "^2.11.5",
        "gerror": "^1.0.16",
        "memory-card": "^1.1.2",
        "state-switch": "^1.7.1",
        "typed-emitter": "^1.5.0-from-event",
        "typesafe-actions": "^5.1.0",
        "uuid": "^8.3.2",
        "watchdog": "^0.9.2"
      },
      "engines": {
        "node": ">=16",
        "npm": ">=7"
      }
    },
    
    
    其它依赖版本信息：
{
  "name": "wechaty-puppet-xp",
  "version": "1.13.8",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "wechaty-puppet-xp",
      "version": "1.13.8",
      "license": "Apache-2.0",
      "dependencies": {
        "cuid": "^2.1.8",
        "sidecar": "^0.17.8",
        "xml2js": "^0.4.23",
        "xmlreader": "^0.2.3"
      },
      "devDependencies": {
        "@chatie/eslint-config": "^1.0.4",
        "@chatie/git-scripts": "^0.7.7",
        "@chatie/semver": "^0.4.7",
        "@chatie/tsconfig": "^4.5.3",
        "@types/cuid": "^2.0.1",
        "@types/faker": "^5.5.9",
        "@types/frida-gum": "^18.5.1",
        "@types/node": "^20.10.5",
        "@types/qrcode-terminal": "^0.12.2",
        "@types/xml2js": "^0.4.9",
        "frida-compile": "^16.4.1",
        "husky": "^7.0.4",
        "qrcode-terminal": "^0.12.0",
        "tstest": "^1.0.1",
        "typed-emitter": "^1.4.0",
        "wechaty": "^1.20.2"
      },
      "engines": {
        "node": ">=16",
        "npm": ">=7"
      },
      "peerDependencies": {
        "wechaty-puppet": "^1.10.2"
      }
    },

**Comment by atorber** [comment]
This issue has been resolved in the latest version.
