### ISSUE TITLE
When multiple messages are forwarded (one by one), the message content cannot be obtained correctly

### ISSUE THREAD

**Issue by 865881900** [wechaty/puppet-xp#19]
environment:

`
  windows 10
  wechat 0.63.7
  node v14.7.0
`

When multiple messages are forwarded (one by one), the message content cannot be obtained correctly

I sent out ten messages in batches and responded correctly to five; 5 items were incorrectly responded;
The contents of two messages were not obtained. The contents of three messages obtained were incorrect

![image](https://user-images.githubusercontent.com/48711726/129992916-64db450c-df15-4821-905b-6dc67656553d.png)

![image](https://user-images.githubusercontent.com/48711726/129992989-ab5e3355-380e-4430-a498-b24a51eb7cda.png)

**Comment by atorber** [comment]
Thanks for your feedback, please provide the test code so that we can reproduce the problem.
