### ISSUE TITLE
Feature request for 'Room Join event'

### ISSUE THREAD

**Issue by Randolph603** [wechaty/puppet-xp#22]
trying the feature of room-join from Wechaty docs, It seems still not implemented.

```
 bot.on('room-join', async any => {
   console.log(`Room join`);
 });
```

Could we enquiry for a feature request?

**Comment by atorber** [comment]
This feature is not supported yet, but it will be solved soon.
Thank you for your attention，we will reply this issue as soon as the it is ready.

**Comment by atorber** [comment]
> trying the feature of room-join from Wechaty docs, It seems still not implemented.
> 
> ```
>  bot.on('room-join', async any => {
>    console.log(`Room join`);
>  });
> ```
> 
> Could we enquiry for a feature request?

@Randolph603 It is already supported, you can have a try.
