### ISSUE TITLE
I encountered some problems in the process of using it

### ISSUE THREAD

**Issue by jiajie99** [wechaty/puppet-xp#78]
11:32:33 ERR SidecarBody [SCRIPT_MESSAGRE_HANDLER_SYMBOL]() MessageType.Error: Error: access violation accessing 0x1588
    at getQrcodeLoginData (/script1.js:618)
    at <anonymous> (/script1.js:607)
    at apply (native)
    at <anonymous> (frida/runtime/core.js:51)
Bot error: undefined

**Comment by ericcug** [comment]
Please provide more details and full log for further investigation.

**Comment by jiajie99** [comment]
Sorry, I can't provide more information. The log is shown in the picture.
![1644587830(1)](https://user-images.githubusercontent.com/56350560/153604445-f79311c9-d9ba-47de-97d9-bac92bb14267.png)

**Comment by ericcug** [comment]
Which version of wechat did you installed? For now, wechaty-puppet-xp only support 3.3.0.115, and can you try to remove node_modules, then npm install?

**Comment by jiajie99** [comment]
The reason for the error is that I didn't use the correct wechat version. Thank you for your answer.

**Comment by zokio** [comment]
个人中心-token管理 获取二维码失败

**Comment by binsee** [comment]
> 个人中心-token管理 获取二维码失败

这个似乎不是 puppet-xp 相关的问题。如果你确定是 puppet-xp 的问题，请单独开一个 issue 详细说明你遇到的问题。

**Comment by zokio** [comment]
> > 个人中心-token管理 获取二维码失败
> 
> 这个似乎不是 puppet-xp 相关的问题。如果你确定是 puppet-xp 的问题，请单独开一个 issue 详细说明你遇到的问题。

我不是在咨询技术问题，是找wechty的售后，我购买的token突然不能用了，以前联系的售后微信不响应了。
