### ISSUE TITLE
when call contact.say(msg) ,  the wechat client shutdown

### ISSUE THREAD

**Issue by lgojc** [wechaty/puppet-xp#86]
#### by follow steps:
1. delete folder \Documents\WeChat Files
2. login wechat( ***do not select sync data*** ) _necessary_
3. contact.say to anybody
```
async function onLogin (user: Contact) {
  log.info('StarterBot', '%s login', user)
  const contactList = await bot.Contact.findAll()
  contactList.forEach(c => {
    if (c.name() === 'A') {
        c.say('hi')
      }
  })

}
```
```
17:48:23 ERR Config Wechaty unhandledRejection: Error: Script is destroyed
    at onScriptDestroyed (D:\Programing\Projects\puppet-xp\node_modules\frida\dist\script.js:118:26) [object Promise]
17:48:23 ERR Config ###########################
17:48:23 ERR Config process.on(unhandledRejection) promise.catch(Script is destroyed)
Config Error: Script is destroyed
    at onScriptDestroyed (D:\Programing\Projects\puppet-xp\node_modules\frida\dist\script.js:118:26)
```
<img width="487" alt="L1VzZXJzL2xpYW5namlhbmNoYW8vTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L0RpbmdUYWxrTWFjLzM1NDQxOTU0X3YyL0ltYWdlRmlsZXMvMTY0NTAwNTY4NTQ0M19GMEE3OUM4NC01OTBDLTRBMTEtQUZEOC05MzI0QzM5N0M1NjMucG5n" src="https://user-images.githubusercontent.com/31304973/154241113-4ef5a287-f1bf-438b-bafb-7d0bc928ec2a.png">

**Comment by starzou** [comment]
The same problem.
